spring:
  application:
    name: Activity-Service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: FitnessApp

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082

