
spring:
  application:
    name: AI-Service
  data:
      mongodb:
        uri: ${MONGO_URI}
        database: FitnessRecommendation
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083