spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_user_db
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8081